SELECT * FROM mydb.retail_sales;
-- create table 
Drop table if exists retail_sales;
create table retail_sales(
transaction int primary key,
sales_date date,
sals_time time,
customer_id int,
gender Varchar(50),
age int,
category varchar(50),
quantity int,
price_per_unit float,
cogs float,
total_sales float
);
SELECT * FROM mydb.retail_sales
limit 20


-- what is total revenue, total order ,and average order value?
select count(*)As total_order,sum(total_sale)As total_revenue,Round(
avg(total_sale),2)As avg_order_value from mydb.retail_sales;


-- How is sales trending month over month?
Select date_format(sale_date,'%y-%m')as month,sum(total_sale)as 
revenue from mydb.retail_sales group by month order by month;


-- what is the total sales generated by the male and female ?
select gender,sum(total_sale) as Total_Sales from
 mydb.retail_sales group by gender;
 
 -- which category have total revenue greater than 30000?
select  category,sum(total_sale) as total_revenue
 from mydb.retail_sales group by category 
 having sum(total_sale)>30000;
 
 
 -- what is the average price per unit for each catgeory?
select category ,avg(price_per_unit) as avg_price
from mydb.retail_sales group by category;


-- which category has a profit margin greater than 40%?
select category ,round(sum(total_sale-cogs)*100/sum(total_sale),2)
as margin_pct from mydb.retail_sales group by category 
having margin_pct>40;


-- which customer are one-time buyer(only 1 order)?
select customer_id ,count(*) as order_count from mydb.retail_sales 
group by customer_id having count(*)=1;


-- Which customers placed more than 20 orders
SELECT customer_id, COUNT(*) AS order_count
FROM mydb.retail_sales
GROUP BY customer_id
HAVING COUNT(*) > 20;
